### ISSUE TITLE
Error When Run

### ISSUE THREAD

**Issue by tomeroto** [holtwick/briefing#134]
Hi friend,

I try install with read documentation and run this command on my UBUNTU.

```
sudo git clone https://github.com/holtwick/briefing.git
cd briefing/
npm install
npm run start
```
and then I see error like this:

```
> briefing@2.1.8 start /var/www/html/nodejs/briefing
> cross-env ZEED=* LEVEL=a zerva src/zerva/index.ts

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/www/html/nodejs/briefing/node_modules/@zerva/bin/bin.cjs:43:12083)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! briefing@2.1.8 start: `cross-env ZEED=* LEVEL=a zerva src/zerva/index.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the briefing@2.1.8 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-02-05T09_18_19_871Z-debug.log
```
Please help, thank you.

**Comment by tomeroto** [comment]
Ok done, I try to upgrade NodeJS by run this command.

```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

thanks for your project its awesome!
