### ISSUE TITLE
red message bar: "An error occured..."

### ISSUE THREAD

**Issue by jangrewe** [holtwick/briefing#152]
Hi, i'm currently testing Briefing on my home server, and it works really well - especially considering the amount of setup required when compared to other projects! ♥️

I've setup websockets proxying and coturn, verified it's working also with external clients, but: i pretty much always get a red error message (`ask_to_send_error`) at the bottom of the screen, stating that an error occurred and that it would like to report that error - which i approve, without anything happening then.

This happens on Chrome and Firefox.

I haven't set a Sentry DSN, so maybe this could be hidden if there's nothing to send to? But i'll look into setting up Sentry to confirm.

**Comment by jangrewe** [comment]
I managed to set up GlitchTip (Sentry has become way too bloated) and was able to catch the error that occurs:

```
AbortError:The fetching process for the media resource was aborted by the user agent at the user's request.
 at doConnectStream/< (/assets/index-327be627.js:68:16419)
 at l (/assets/index-327be627.js:1:723)
 at promise callback*f (/assets/index-327be627.js:1:836)
 at Ke/< (/assets/index-327be627.js:1:847)
 at Ke (/assets/index-327be627.js:1:685)
 at doConnectStream (/assets/index-327be627.js:68:16246)
 at stream (/assets/index-327be627.js:68:15951)
 at Nr (/assets/index-327be627.js:1:14341)
 at Un (/assets/index-327be627.js:1:14422)
 at G (/assets/index-327be627.js:1:19685)
 at nh (/assets/index-327be627.js:1:15548)
 at he (/assets/index-327be627.js:1:38943)
 at ae (/assets/index-327be627.js:1:37947)
 at run (/assets/index-327be627.js:1:6296)
 at Z3/$e/y.update (/assets/index-327be627.js:1:38799)
 at je (/assets/index-327be627.js:1:37786)
 at we (/assets/index-327be627.js:1:37429)
 at V (/assets/index-327be627.js:1:34162)
 at J (/assets/index-327be627.js:1:36638)
 at A (/assets/index-327be627.js:1:35969)
 at S (/assets/index-327be627.js:1:34741)
 at V (/assets/index-327be627.js:1:34134)
 at ae (/assets/index-327be627.js:1:38081)
 at run (/assets/index-327be627.js:1:6296)
 at Z3/$e/y.update (/assets/index-327be627.js:1:38799)
 at Nr (/assets/index-327be627.js:1:14349)
 at ap (/assets/index-327be627.js:1:15981)
 at promise callback*sp (/assets/index-327be627.js:1:15289)
 at zu (/assets/index-327be627.js:1:15246)
 at Z3/$e/y.effect< (/assets/index-327be627.js:1:38768)
 at Jd (/assets/index-327be627.js:1:7632)
 at ru (/assets/index-327be627.js:1:7568)
 at hr (/assets/index-327be627.js:1:7395)
 at jg/< (/assets/index-327be627.js:1:9015)
 at sc/< (/assets/index-327be627.js:28:28073)
 at l (/assets/index-327be627.js:1:723)
 at promise callback*f (/assets/index-327be627.js:1:836)
 at Ke/< (/assets/index-327be627.js:1:847)
 at Ke (/assets/index-327be627.js:1:685)
 at sc (/assets/index-327be627.js:28:27266)
 at setTimeout handler*w8/< (/assets/index-327be627.js:32:415)
 at l (/assets/index-327be627.js:1:723)
 at promise callback*f (/assets/index-327be627.js:1:836)
 at l (/assets/index-327be627.js:1:720)
 at promise callback*f (/assets/index-327be627.js:1:836)
 at l (/assets/index-327be627.js:1:720)
 at promise callback*f (/assets/index-327be627.js:1:836)
 at Ke/< (/assets/index-327be627.js:1:847)
 at Ke (/assets/index-327be627.js:1:685)
 at w8 (/assets/index-327be627.js:28:28149) 
```
It seems to be `MEDIA_ERR_ABORTED`: https://www.w3.org/TR/2010/WD-html5-20100304/video.html
Maybe this is of help? https://github.com/elan-ev/opencast-studio/issues/581

The video does work fine, though! The error is just a bit annoying. 😀
